export const SET_FILTER = "SET_FILTER";
export const SET_RADIO_FILTER ="SET_RADIO_FILTER"
export const CREATE_CLINIC_ACTION = "CREATE_CLINIC_ACTION"
export const FIND_CLINIC_ACTION = "FIND_CLINIC_ACTION"
export const SET_LOCATION_ACTION = "SET_LOCATION_ACTION"